{"name": "Тест авторизация с неверным логином", "status": "passed", "start": 1707828941386, "stop": 1707828941803, "uuid": "cae45bfc-a307-402f-92ec-3e14b51e11e0", "historyId": "2fc6b0e4ea05308707e665b2f4cdd512", "testCaseId": "2fc6b0e4ea05308707e665b2f4cdd512", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_incorrect_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-1KK7H688"}, {"name": "thread", "value": "21644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}